Add the QMX codec as a block codec option
ot/ds2i pull request #3
Opened 2017-12-09 08:11 UTC by mpetri

This adds QMX as a potential block codec to ds2i. QMX is a SIMD based
simple16 codec. Some of the tricks in QMX can't be used here as we are
only using it to compress small blocks. Still it looks like it is quite
fast in practice. Here some performance numbers on GOV2:

Construction and Space:

OPTPFOR:

```
2017-12-09 14:51:41: block_optpfor collection built in 333.281 seconds
{"type": "block_optpfor", "worker_threads": 32, "construction_time": 333.281, "construction_user_time": 326.929}
<TOP>: 4721294275
    m_params: 5
    m_endpoints: 30417976
        m_bits: 30417968
    m_lists: 4690876278
2017-12-09 14:52:02: Documents: 3076708620 bytes, 4.54465 bits per element
2017-12-09 14:52:02: Frequencies: 1614167658 bytes, 2.38431 bits per element
{"type": "block_optpfor", "size": 4690876278, "docs_size": 3076708620, "freqs_size": 1614167658, "bits_per_doc": 4.54465, "bits_per_freq": 2.38431}
```

EFOPT:

```
2017-12-08 15:08:58: opt collection built in 431.922 seconds
{"type": "opt", "worker_threads": 32, "construction_time": 431.922, "construction_user_time": 6850.5}
<TOP>: 4416874709
    m_params: 5
    m_docs_sequences: 2825786736
        m_endpoints: 37670320
            m_bits: 37670312
        m_bitvectors: 2788116408
            m_bits: 2788116400
    m_freqs_sequences: 1591087960
        m_endpoints: 35175480
            m_bits: 35175472
        m_bitvectors: 1555912472
            m_bits: 1555912464
2017-12-08 15:08:58: Documents: 2825786736 bytes, 4.17401 bits per element
2017-12-08 15:08:58: Frequencies: 1591087960 bytes, 2.35022 bits per element
{"type": "opt", "size": 4416874696, "docs_size": 2825786736, "freqs_size": 1591087960, "bits_per_doc": 4.17401, "bits_per_freq": 2.35022}
{"type": "opt", "eps1": 0.03, "eps2": 0.3, "fix_cost": 64, "docs_avg_part": 218.16, "freqs_avg_part": 458.268}
```

VARINT:

```
2017-12-08 15:14:34: block_varint collection built in 73.4144 seconds
{"type": "block_varint", "worker_threads": 32, "construction_time": 73.4144, "construction_user_time": 59.3292}
<TOP>: 12997974606
    m_params: 5
    m_endpoints: 35250704
        m_bits: 35250696
    m_lists: 12962723881
2017-12-08 15:14:45: Documents: 6985515548 bytes, 10.3184 bits per element
2017-12-08 15:14:45: Frequencies: 5977208333 bytes, 8.82902 bits per element
{"type": "block_varint", "size": 12962723881, "docs_size": 6985515548, "freqs_size": 5977208333, "bits_per_doc": 10.3184, "bits_per_freq": 8.82902}
```

QMX:

```
2017-12-08 15:12:17: block_qmx collection built in 120.057 seconds
{"type": "block_qmx", "worker_threads": 32, "construction_time": 120.057, "construction_user_time": 111.772}
<TOP>: 6464367218
    m_params: 5
    m_endpoints: 32229384
        m_bits: 32229376
    m_lists: 6432137813
2017-12-08 15:12:32: Documents: 4132501281 bytes, 6.10417 bits per element
2017-12-08 15:12:32: Frequencies: 2299636532 bytes, 3.39682 bits per element
{"type": "block_qmx", "size": 6432137813, "docs_size": 4132501281, "freqs_size": 2299636532, "bits_per_doc": 6.10417, "bits_per_freq": 3.39682}
```

Query time:

```
mpetri@raksasa:~/ds2i/build$ bash ./test.sh
2017-12-08 16:32:13: Loading index from ./gov2.efopt
2017-12-08 16:32:13: Warming up posting lists
2017-12-08 16:32:13: Performing opt queries
2017-12-08 16:32:13: Query type: wand
2017-12-08 16:50:56: ---- opt wand
2017-12-08 16:50:56: Mean: 8462.57
2017-12-08 16:50:56: 50% quantile: 2656
2017-12-08 16:50:56: 90% quantile: 20865
2017-12-08 16:50:56: 95% quantile: 35459
{"type": "opt", "query": "wand", "avg": 8462.57, "q50": 2656, "q90": 20865, "q95": 35459}
2017-12-08 16:50:56: Loading index from ./gov2.qmx
2017-12-08 16:50:56: Warming up posting lists
2017-12-08 16:50:58: Performing block_qmx queries
2017-12-08 16:50:58: Query type: wand
2017-12-08 17:04:40: ---- block_qmx wand
2017-12-08 17:04:40: Mean: 6171.27
2017-12-08 17:04:40: 50% quantile: 2178
2017-12-08 17:04:40: 90% quantile: 15713
2017-12-08 17:04:40: 95% quantile: 24823
{"type": "block_qmx", "query": "wand", "avg": 6171.27, "q50": 2178, "q90": 15713, "q95": 24823}
2017-12-08 17:04:40: Loading index from ./gov2.varint
2017-12-08 17:04:40: Warming up posting lists
2017-12-08 17:04:44: Performing block_varint queries
2017-12-08 17:04:44: Query type: wand
2017-12-08 17:16:13: ---- block_varint wand
2017-12-08 17:16:13: Mean: 5178.64
2017-12-08 17:16:13: 50% quantile: 1741
2017-12-08 17:16:13: 90% quantile: 12853
2017-12-08 17:16:13: 95% quantile: 21156
{"type": "block_varint", "query": "wand", "avg": 5178.64, "q50": 1741, "q90": 12853, "q95": 21156}
2017-12-09 16:24:26: Loading index from ./gov2.opf
2017-12-09 16:24:26: Warming up posting lists
2017-12-09 16:24:27: Performing block_optpfor queries
2017-12-09 16:24:27: Query type: wand
2017-12-09 16:41:39: ---- block_optpfor wand
2017-12-09 16:41:39: Mean: 7747.26
2017-12-09 16:41:39: 50% quantile: 2678
2017-12-09 16:41:39: 90% quantile: 20005
2017-12-09 16:41:39: 95% quantile: 32275
{"type": "block_optpfor", "query": "wand", "avg": 7747.26, "q50": 2678, "q90": 20005, "q95": 32275}
```

All tests pass on my machine.

This is with blocksize 128 which is bad for QMX. Still performance is quite good.

2017-12-09 08:11 UTC, mpetri commented
Maybe some #ifdefs should be added to only enable this if CPU support is there...

2017-12-26 14:28 UTC, amallia requested changes
Building in Debug mode and running tests I get:
```
Running 1 test case...
test_block_codecs(4008,0x7fff89c04340) malloc: *** error for object 0x7fbd75d01728: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
unknown location:0: fatal error: in "block_codecs": signal: illegal opcode; address of failing instruction: 0x7fff50d745e2
/Users/amallia/Development/ds2i/test/test_block_codecs.cpp:34: last checkpoint
Illegal instruction: 4
```

I haven't investigated any further yet.

2017-12-27 01:28 UTC, mpetri commented
Thanks @amallia ! I think this is related to the include guards I mentioned I still have to add if the CPU doesn't support the instructions required by the new method.

2017-12-27 01:41 UTC, amallia commented
I suppose QMX needs SSE4.1 and SSE2 as it includes `emmintrin.h` and  `smmintrin.h` which my CPU supports. 

I think the issue is something else, but some include guards are definitely needed anyway.
Thanks

2017-12-27 02:16 UTC, mpetri commented
This should fix the issue. The tests did not account for the necessary extra space as QMX can overshoot during decoding. Still have to add the include guards.

2017-12-27 02:20 UTC, amallia commented
Tests passing now. Thank you

2017-12-27 04:40 UTC, mpetri commented
I think I'll merge this now as other stuff doesn't compile as well if SSE4.X is not available.

2017-12-27 04:42 UTC, merged

2018-08-06 06:53 UTC, amallia commented
@mpetri Sorry for re-opening this.
Since you have attached to the present some performance test measures. Could you let me know what CPU did you run it on? Thanks

2018-08-06 06:59 UTC, mpetri commented
I can't be sure but I think it was a Intel(R) Xeon(R) Gold 6144 CPU @ 3.50GHz

2018-08-06 07:03 UTC, amallia commented
Thanks! 
I am running it on a i7 4770 @ 3.40GHz and I am getting slower results indeed. Probably because of the bigger cache more than the clock freq.